### ISSUE TITLE
[question] cannot run jnaerator

### ISSUE THREAD

**Issue by Airblader** [ochafik/JNAerator#3]
This is almost surely a problem on my side, but I can't manage to run JNAerator correctly. All the FAQ simply run `jnaerator.jar`, but I just cloned & built the repository and the only JAR files that come close are `jnaerator-0.13-SNAPSHOT.jar` and `jnaerator-parser-0.13-SNAPSHOT.jar`.

However, when I use those to run it, I get a "java.lang.NoClassDefFoundError: com/ochafik/lang/jnaerator/parser/Visitor" and "no main manifest attribute, in jnaerator-parser-0.13-SNAPSHOT.jar" respectively.

What am I doing wrong? For completeness, the command I ran was

````
java -jar $WHATEVER.jar -library xcb xcb.h libxcb.so -mode StandaloneJar
```

Running Oracle JDK 1.8.0_40.

**Comment by Airblader** [comment]
I got it to work (I think – at least it ran through, but I haven't verified the result yet) with

````
CLASSPATH=.; export CLASSPATH=$CLASSPATH$(find "$PWD" -name '*.jar' -type f -printf ':%p\n' | sort -u | tr -d '\n'); echo $CLASSPATH
java com.ochafik.lang.jnaerator.JNAerator /usr/include/xcb/xcb.h /usr/lib64/libxcb.so -mode StandaloneJar
```

This seems pretty hacky, though. I'm sure there's a better way?

**Comment by ochafik** [comment]
Hi @Airblader ,

The jar you should use is the -shaded.jar one (which includes all dependencies).
I should definitely make this clearer in the wiki / doc, will keep this issue open until it is :-)

Cheers

**Comment by Airblader** [comment]
Thanks for your reply. I tried again, but I'm still having problems :(

````
┏━[ ingo@buerk ]━[ ~/repos/JNAerator ]━[  master ? ]
┗━[ java -jar ./jnaerator-runtime/target/jnaerator-runtime-0.13-SNAPSHOT-shaded.jar /usr/include/xcb/xcb.h /usr/lib64/libxcb.so -mode StandaloneJar
no main manifest attribute, in ./jnaerator-runtime/target/jnaerator-runtime-0.13-SNAPSHOT-shaded.jar
```

**Comment by ochafik** [comment]
Hehe, sorry for incomplete hint, I meant [jnaerator-0.13-SNAPSHOT-shaded.jar](https://oss.sonatype.org/service/local/repositories/snapshots/content/com/nativelibs4java/jnaerator/0.13-SNAPSHOT/jnaerator-0.13-20150311.101753-1-shaded.jar)

(jnaerator-runtime only contains a JNA runtime extension, definitely need to make things less ambiguous)

**Comment by Airblader** [comment]
Ah, alright. Now it finally worked. Thank you!
